#!/usr/bin/env python3
"""
Generate the LaTeX result tables for the empirical paper from the committed
result JSONs in experiments/results/. Every number in the paper's result
tables comes from this script, so the tables cannot drift from the evidence
without the diff showing it.

Outputs (all under paper/tables/):
  tab_clean_detection.tex    <- trajectory_lift.json
  tab_minhash_frontier.tex   <- m3_frontier.json
  tab_perturbation_sweep.tex <- perturbation_sweep.json
  tab_fp_substrate.tex       <- fp_substrate.json

Usage: python3 scripts/build_paper_tables.py
"""

import json
from pathlib import Path

ROOT = Path(__file__).resolve().parent.parent
RESULTS = ROOT / "experiments" / "results"
OUT = ROOT / "paper" / "tables"
OUT.mkdir(parents=True, exist_ok=True)


def load(name):
    with open(RESULTS / name) as fh:
        return json.load(fh)


def write(name, source, body):
    header = (f"% Auto-generated by scripts/build_paper_tables.py\n"
              f"% Source of truth: experiments/results/{source}\n"
              f"% Do not edit by hand; re-run the script instead.\n")
    (OUT / name).write_text(header + body)
    print(f"  wrote paper/tables/{name}  (from {source})")


def tab_clean_detection():
    t = load("trajectory_lift.json")
    b, s = t["baseline"], t["sequence_model"]
    lift = t["key_metric"]["value"]
    lo, hi = t["key_metric"]["bootstrap_95ci"]
    rows = "\n".join([
        f"Per-message LinearSVC & {b['auc_roc']:.3f} & {b['recall_at_fpr_target']:.3f} "
        f"& {b['precision_at_fpr_target']:.3f} & {b['f1_at_fpr_target']:.3f} \\\\",
        f"Sequence model & {s['auc_roc']:.3f} & {s['recall_at_fpr_target']:.3f} "
        f"& {s['precision_at_fpr_target']:.3f} & {s['f1_at_fpr_target']:.3f} \\\\",
    ])
    body = (
        "\\begin{tabular}{@{}l c c c c@{}}\n\\toprule\n"
        "Model & AUC & Recall & Precision & F1 \\\\\n"
        "\\midrule\n" + rows + "\n\\midrule\n"
        f"\\multicolumn{{5}}{{@{{}}l}}{{Sequence-over-baseline F1 lift: "
        f"${lift:.3f}$, bootstrap 95\\% CI $[{lo:.3f},\\,{hi:.3f}]$}} \\\\\n"
        "\\bottomrule\n\\end{tabular}\n")
    write("tab_clean_detection.tex", "trajectory_lift.json", body)


def tab_minhash_frontier():
    m = load("m3_frontier.json")
    rows = "\n".join(
        f"{p['b']} & {p['r']} & {(1/p['b'])**(1/p['r']):.3f} & "
        f"{p['federated_recall']:.4f} & {p['federated_fpr']:.4f} \\\\"
        for p in m["operating_points"])
    body = (
        "\\begin{tabular}{@{}c c c c c@{}}\n\\toprule\n"
        "$b$ & $r$ & Inflection $J^\\star$ & Recall & FPR \\\\\n"
        "\\midrule\n" + rows + "\n\\bottomrule\n\\end{tabular}\n")
    write("tab_minhash_frontier.tex", "m3_frontier.json", body)


def tab_perturbation_sweep():
    s = load("perturbation_sweep.json")
    cond = {c["strength_name"]: c for c in s["conditions"]}
    base0 = cond["none"]["baseline"]["auc"]["mean"]
    seq0 = cond["none"]["sequence"]["auc"]["mean"]
    rows = []
    for name in ("none", "light", "medium", "heavy"):
        c = cond[name]
        ba, sa = c["baseline"]["auc"], c["sequence"]["auc"]
        bd, sd = base0 - ba["mean"], seq0 - sa["mean"]
        std_b = f" $\\pm$ {ba['std']:.3f}" if name != "none" else ""
        std_s = f" $\\pm$ {sa['std']:.3f}" if name != "none" else ""
        rows.append(
            f"{name} & {c['strength']:.2f} & {ba['mean']:.3f}{std_b} & {bd:.3f} "
            f"& {sa['mean']:.3f}{std_s} & {sd:.3f} \\\\")
    body = (
        "\\begin{tabular}{@{}l c c c c c@{}}\n\\toprule\n"
        " & & \\multicolumn{2}{c}{Per-message baseline} & "
        "\\multicolumn{2}{c}{Sequence model} \\\\\n"
        "\\cmidrule(lr){3-4}\\cmidrule(lr){5-6}\n"
        "Strength & $p$ & AUC & Drop & AUC & Drop \\\\\n"
        "\\midrule\n" + "\n".join(rows) + "\n\\bottomrule\n\\end{tabular}\n")
    write("tab_perturbation_sweep.tex", "perturbation_sweep.json", body)


def tab_fp_substrate():
    f = load("fp_substrate.json")
    s = f["summary"]

    def ci(x):
        return f"[{x[0]:.3f},\\,{x[1]:.3f}]"

    rows = []
    for det, label in (("minhash_16_16", "MinHash $(b{=}16, r{=}16)$"),
                       ("classifier_fpr05",
                        "LinearSVC @ FPR$\\leq$0.05")):
        d = s[det]
        rows.append(
            f"{label} & {d['structural_FPR_mean']:.3f} "
            f"{ci(d['structural_FPR_pooled_wilson95'])} & "
            f"{d['control_FPR_mean']:.3f} "
            f"{ci(d['control_FPR_pooled_wilson95'])} \\\\")
    body = (
        "\\begin{tabular}{@{}l c c@{}}\n\\toprule\n"
        "Detector & \\makecell{Structurally similar benign \\\\ FPR "
        "[pooled Wilson 95\\% CI]} & \\makecell{Random benign control \\\\ "
        "FPR [pooled Wilson 95\\% CI]} \\\\\n"
        "\\midrule\n" + "\n".join(rows) + "\n\\bottomrule\n\\end{tabular}\n")
    write("tab_fp_substrate.tex", "fp_substrate.json", body)


def tab_perturbation_author_disjoint():
    s = load("perturbation_sweep_author_disjoint.json")
    cond = {c["strength_name"]: c for c in s["conditions"]}
    base0 = cond["none"]["baseline"]["auc"]["mean"]
    seq0 = cond["none"]["sequence"]["auc"]["mean"]
    rows = []
    for name in ("none", "light", "medium", "heavy"):
        c = cond[name]
        ba, sa = c["baseline"]["auc"], c["sequence"]["auc"]
        bd, sd = base0 - ba["mean"], seq0 - sa["mean"]
        std_b = f" $\\pm$ {ba['std']:.3f}" if name != "none" else ""
        std_s = f" $\\pm$ {sa['std']:.3f}" if name != "none" else ""
        rows.append(
            f"{name} & {c['strength']:.2f} & {ba['mean']:.3f}{std_b} & {bd:.3f} "
            f"& {sa['mean']:.3f}{std_s} & {sd:.3f} \\\\")
    body = (
        "\\begin{tabular}{@{}l c c c c c@{}}\n\\toprule\n"
        " & & \\multicolumn{2}{c}{Per-message baseline} & "
        "\\multicolumn{2}{c}{Sequence model} \\\\\n"
        "\\cmidrule(lr){3-4}\\cmidrule(lr){5-6}\n"
        "Strength & $p$ & AUC & Drop & AUC & Drop \\\\\n"
        "\\midrule\n" + "\n".join(rows) + "\n\\bottomrule\n\\end{tabular}\n")
    write("tab_perturbation_author_disjoint.tex",
          "perturbation_sweep_author_disjoint.json", body)


CONTROL_LABELS = [
    ("per_message_mean", "Per-message mean (baseline)"),
    ("per_message_max", "Per-message max"),
    ("per_message_top5", "Per-message top-5 mean"),
    ("conv_concat", "Conversation concat (order-inv.)"),
    ("conv_mean", "Conversation mean (order-inv.)"),
    ("sequence", "Sequence (position-weighted)"),
    ("sequence_shuffled", "Sequence, shuffled order (control)"),
]


def _tab_controls(json_name, tex_name):
    d = load(json_name)
    deg = {row["strength_name"]: row["models"] for row in d["degradation"]}
    clean = {m: deg["light"][m]["auc_clean"] for m, _ in CONTROL_LABELS}
    rows = []
    for m, label in CONTROL_LABELS:
        cells = [f"{clean[m]:.3f}"]
        for s in ("light", "medium", "heavy"):
            cells.append(f"{deg[s][m]['auc_drop']:.3f}")
        bold = m == "sequence"
        lbl = f"\\textbf{{{label}}}" if bold else label
        rows.append(lbl + " & " + " & ".join(cells) + " \\\\")
    body = (
        "\\begin{tabular}{@{}l c c c c@{}}\n\\toprule\n"
        " & Clean & \\multicolumn{3}{c}{AUC drop at strength} \\\\\n"
        "\\cmidrule(lr){3-5}\n"
        "Model / control & AUC & light & medium & heavy \\\\\n"
        "\\midrule\n" + "\n".join(rows) + "\n\\bottomrule\n\\end{tabular}\n")
    write(tex_name, json_name, body)


def tab_perturbation_controls():
    _tab_controls("perturbation_model_controls.json",
                  "tab_perturbation_controls.tex")


def tab_perturbation_second_family():
    _tab_controls("perturbation_second_family.json",
                  "tab_perturbation_second_family.tex")


def tab_perturbation_sweeps_merged():
    """Both sweep splits in one column-width-friendly table (USENIX draft)."""
    conv = {c["strength_name"]: c
            for c in load("perturbation_sweep.json")["conditions"]}
    adj = {c["strength_name"]: c
           for c in load("perturbation_sweep_author_disjoint.json")["conditions"]}
    rows = []
    for name in ("none", "light", "medium", "heavy"):
        cells = [name]
        for cond in (conv, adj):
            c0 = cond["none"]
            c = cond[name]
            for model in ("baseline", "sequence"):
                auc = c[model]["auc"]["mean"]
                drop = c0[model]["auc"]["mean"] - auc
                cells.append(f"{auc:.3f}" if name == "none"
                             else f"{auc:.3f} ({drop:.3f})")
        rows.append(" & ".join(cells) + " \\\\")
    body = (
        "\\begin{tabular}{@{}l cc cc@{}}\n\\toprule\n"
        " & \\multicolumn{2}{c}{Conversation-level split} & "
        "\\multicolumn{2}{c}{Author-disjoint split} \\\\\n"
        "\\cmidrule(lr){2-3}\\cmidrule(lr){4-5}\n"
        "Strength & Per-msg & Sequence & Per-msg & Sequence \\\\\n"
        "\\midrule\n" + "\n".join(rows) + "\n\\bottomrule\n\\end{tabular}\n")
    write("tab_perturbation_sweeps_merged.tex",
          "perturbation_sweep.json + perturbation_sweep_author_disjoint.json",
          body)


def tab_perturbation_paired_tests():
    d = load("perturbation_paired_tests.json")
    label = {
        "per_message_mean": "vs.\\ per-message mean (baseline)",
        "per_message_max": "vs.\\ per-message max",
        "per_message_top5": "vs.\\ per-message top-5 mean",
        "conv_concat": "vs.\\ conversation concat (order-inv.)",
        "conv_mean": "vs.\\ conversation mean (order-inv.)",
    }
    rows = []
    for comp, per_strength in d["comparisons"].items():
        cells = []
        for s in ("light", "medium", "heavy"):
            r = per_strength[s]
            lo, hi = r["ci95"]
            mark = "$^*$" if r["ci_excludes_zero"] else ""
            cells.append(f"$[{lo:+.4f}, {hi:+.4f}]${mark}")
        rows.append(f"{label[comp]} & " + " & ".join(cells) + " \\\\")
    body = (
        "\\begin{tabular}{@{}l c c c@{}}\n\\toprule\n"
        "Comparison & light & medium & heavy \\\\\n"
        "\\midrule\n" + "\n".join(rows) + "\n\\bottomrule\n\\end{tabular}\n")
    write("tab_perturbation_paired_tests.tex",
          "perturbation_paired_tests.json", body)


def main():
    print("Generating paper tables from experiments/results/*.json ...")
    tab_clean_detection()
    tab_minhash_frontier()
    tab_perturbation_sweep()
    tab_fp_substrate()
    for fn in (tab_perturbation_author_disjoint, tab_perturbation_controls,
               tab_perturbation_paired_tests, tab_perturbation_second_family,
               tab_perturbation_sweeps_merged):
        try:
            fn()
        except FileNotFoundError as exc:
            print(f"  SKIP {fn.__name__}: source JSON not found ({exc.filename})")
    print("Done.")


if __name__ == "__main__":
    main()
